import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#0b1020' },
  header: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 8, flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between' },
  headerLeft: { flex: 1, paddingRight: 10 },
  headerActions: { flexDirection: 'row', gap: 8 },
  title: { color: '#e5e7eb', fontSize: 28, fontWeight: '700' },
  subtitle: { color: '#94a3b8', marginTop: 2 },
  menuButton: { borderWidth: 1, borderColor: '#334155', borderRadius: 8, width: 40, height: 40, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0f172a' },
  menuButtonText: { color: '#e5e7eb', fontSize: 18, fontWeight: '700' },
  filters: { paddingHorizontal: 12, gap: 8 },
  row: { flexDirection: 'row', gap: 8 },
  input: { flex: 1, borderWidth: 1, borderColor: '#334155', backgroundColor: '#0f172a', color: '#e5e7eb', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 8 },
  genreButton: { borderWidth: 1, borderColor: '#334155', backgroundColor: '#0f172a', borderRadius: 8, padding: 10 },
  genreButtonText: { color: '#e5e7eb' },
  button: { flex: 1, backgroundColor: '#22d3ee', borderRadius: 8, paddingVertical: 10, alignItems: 'center' },
  buttonText: { color: '#042f2e', fontWeight: '700' },
  ghostButton: { flex: 1, borderWidth: 1, borderColor: '#334155', borderRadius: 8, paddingVertical: 10, alignItems: 'center' },
  ghostButtonText: { color: '#cbd5e1', fontWeight: '600' },
  error: { color: '#fca5a5', paddingHorizontal: 12, marginTop: 8 },
  grid: { padding: 12, gap: 12 },
  card: { flex: 1, margin: 6, borderWidth: 1, borderColor: '#1f2937', borderRadius: 12, backgroundColor: '#111827', overflow: 'hidden', height: 390 },
  cardFlipContainer: { flex: 1 },
  cardFace: { position: 'absolute', width: '100%', height: '100%', backfaceVisibility: 'hidden' },
  cardFrontFace: { backgroundColor: '#111827' },
  cardBackFace: { backgroundColor: '#111827' },
  cardBack: { flex: 1, padding: 10 },
  poster: { width: '100%', height: 250, backgroundColor: '#0f172a' },
  movieTitle: { color: '#e5e7eb', fontSize: 14, paddingHorizontal: 8, paddingTop: 8, minHeight: 38 },
  metaRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 8, paddingTop: 2, paddingBottom: 8 },
  tag: { color: '#94a3b8', fontSize: 12 },
  ratingTag: { color: '#94a3b8', fontSize: 11 },
  cardActions: { flexDirection: 'row', gap: 8, padding: 8 },
  iconButton: { flex: 1, borderRadius: 8, borderWidth: 1, paddingVertical: 8, alignItems: 'center', justifyContent: 'center' },
  acceptButton: { borderColor: '#166534', backgroundColor: '#15803d' },
  rejectButton: { borderColor: '#991b1b', backgroundColor: '#b91c1c' },
  toWatchIconButton: { borderColor: '#0e7490', backgroundColor: '#155e75' },
  iconButtonText: { color: '#e5e7eb', fontWeight: '700', fontSize: 16 },
  cardBackScrollContent: { paddingBottom: 8 },
  detailLine: { color: '#94a3b8', fontSize: 12, paddingHorizontal: 8, marginBottom: 4 },
  overviewText: { color: '#cbd5e1', fontSize: 12, lineHeight: 18, paddingHorizontal: 8, marginTop: 6 },
  footer: { alignItems: 'center', marginVertical: 12, gap: 10 },
  loader: { marginTop: 4 },
  emptyState: { paddingHorizontal: 24, paddingVertical: 40, alignItems: 'center', gap: 12 },
  emptyStateTitle: { color: '#e5e7eb', fontSize: 16, fontWeight: '700', textAlign: 'center' },
  emptyStateText: { color: '#94a3b8', fontSize: 13, lineHeight: 19, textAlign: 'center' },
  emptyStateButton: { flex: 0, minWidth: 150, paddingHorizontal: 18 },
  menuBackdrop: { flex: 1, backgroundColor: 'rgba(2, 6, 23, 0.35)', alignItems: 'flex-end', paddingTop: 56, paddingRight: 16 },
  menuPanel: { width: 170, borderWidth: 1, borderColor: '#1f2937', borderRadius: 10, overflow: 'hidden', backgroundColor: '#111827' },
  menuItem: { paddingVertical: 12, paddingHorizontal: 14, borderBottomWidth: 1, borderBottomColor: '#1f2937' },
  menuItemText: { color: '#e5e7eb', fontWeight: '600' },
  toWatchList: { padding: 12, gap: 10 },
  toWatchCard: { borderWidth: 1, borderColor: '#1f2937', borderRadius: 12, backgroundColor: '#111827', flexDirection: 'row', overflow: 'hidden' },
  toWatchPoster: { width: 96, height: 144, backgroundColor: '#0f172a' },
  toWatchMeta: { flex: 1, padding: 10 },
  toWatchActions: { flexDirection: 'row', gap: 8, marginTop: 8 },
  removeButton: { borderColor: '#334155', backgroundColor: '#0f172a' },
  emptyText: { color: '#94a3b8', textAlign: 'center', marginTop: 30 },
  modalBackdrop: { flex: 1, backgroundColor: 'rgba(2, 6, 23, 0.8)', justifyContent: 'flex-end' },
  modalPanel: { backgroundColor: '#111827', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 14, maxHeight: '72%' },
  modalTitle: { color: '#e5e7eb', fontWeight: '700', fontSize: 18, marginBottom: 8 },
  genreList: { marginBottom: 12 },
  genreItem: { flexDirection: 'row', justifyContent: 'space-between', borderBottomWidth: 1, borderBottomColor: '#1f2937', paddingVertical: 10 },
  genreItemText: { color: '#e5e7eb' },
  genreCheckOn: { color: '#22d3ee', fontWeight: '700' },
  genreCheckOff: { color: '#64748b' },
});
