// Plain CSS-in-JS objects (no React Native StyleSheet)
export const styles = {
  container: { display: 'flex', flexDirection: 'column', height: '100vh', backgroundColor: '#0b1020', overflow: 'hidden' },

  header: { display: 'flex', flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', padding: '12px 16px 8px' },
  headerLeft: { flex: 1, paddingRight: 10 },
  headerActions: { display: 'flex', flexDirection: 'row', gap: 8 },
  title: { color: '#e5e7eb', fontSize: 28, fontWeight: 700, margin: 0 },
  subtitle: { color: '#94a3b8', marginTop: 2, margin: '2px 0 0' },

  menuButton: { border: '1px solid #334155', borderRadius: 8, width: 40, height: 40, display: 'flex', alignItems: 'center', justifyContent: 'center', backgroundColor: '#0f172a', cursor: 'pointer', flexShrink: 0 },
  menuButtonText: { color: '#e5e7eb', fontSize: 18, fontWeight: 700, margin: 0 },

  filters: { padding: '0 12px', display: 'flex', flexDirection: 'column', gap: 8, paddingBottom: 8 },
  row: { display: 'flex', flexDirection: 'row', gap: 8 },
  input: { flex: 1, border: '1px solid #334155', backgroundColor: '#0f172a', color: '#e5e7eb', borderRadius: 8, padding: '8px 10px', fontSize: 14, outline: 'none', minWidth: 0 },
  genreButton: { border: '1px solid #334155', backgroundColor: '#0f172a', borderRadius: 8, padding: 10, cursor: 'pointer', textAlign: 'left', width: '100%' },
  genreButtonText: { color: '#e5e7eb', overflow: 'hidden', whiteSpace: 'nowrap', textOverflow: 'ellipsis', margin: 0, display: 'block' },

  button: { flex: 1, backgroundColor: '#22d3ee', borderRadius: 8, padding: '10px 0', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', border: 'none' },
  buttonText: { color: '#042f2e', fontWeight: 700, margin: 0 },
  ghostButton: { flex: 1, border: '1px solid #334155', borderRadius: 8, padding: '10px 0', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer', backgroundColor: 'transparent' },
  ghostButtonText: { color: '#cbd5e1', fontWeight: 600, margin: 0 },

  error: { color: '#fca5a5', padding: '8px 12px 0', margin: 0 },

  grid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', padding: 12, gap: 12 },
  card: { border: '1px solid #1f2937', borderRadius: 12, backgroundColor: '#111827', overflow: 'hidden', height: 390, display: 'flex', flexDirection: 'column', perspective: '1000px' },
  cardFlipContainer: { flex: 1, position: 'relative' },
  cardFace: { position: 'absolute', top: 0, left: 0, width: '100%', height: '100%', backfaceVisibility: 'hidden', WebkitBackfaceVisibility: 'hidden', transition: 'opacity 0.2s' },
  cardFrontFace: { backgroundColor: '#111827', display: 'flex', flexDirection: 'column' },
  cardBackFace: { backgroundColor: '#111827', display: 'flex', flexDirection: 'column', overflowY: 'auto' },
  cardBack: { flex: 1, padding: 10, display: 'flex', flexDirection: 'column' },
  poster: { width: '100%', height: 250, backgroundColor: '#0f172a', objectFit: 'cover', display: 'block' },
  movieTitle: { color: '#e5e7eb', fontSize: 14, padding: '8px 8px 0', minHeight: 38, overflow: 'hidden', display: '-webkit-box', WebkitLineClamp: 2, WebkitBoxOrient: 'vertical', margin: 0 },
  metaRow: { display: 'flex', flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: '2px 8px 8px' },
  tag: { color: '#94a3b8', fontSize: 12, margin: 0 },
  ratingTag: { color: '#94a3b8', fontSize: 11, margin: 0 },
  cardActions: { display: 'flex', flexDirection: 'row', padding: '0 8px 8px', justifyContent: 'space-between' },
  iconButton: { width: '31%', borderRadius: 8, padding: '8px 0', display: 'flex', alignItems: 'center', justifyContent: 'center', cursor: 'pointer' },
  acceptButton: { border: '1px solid #166534', backgroundColor: '#15803d' },
  rejectButton: { border: '1px solid #991b1b', backgroundColor: '#b91c1c' },
  toWatchIconButton: { border: '1px solid #0e7490', backgroundColor: '#155e75' },
  iconButtonText: { color: '#e5e7eb', fontWeight: 700, fontSize: 16, margin: 0 },
  detailLine: { color: '#94a3b8', fontSize: 12, padding: '0 8px', marginBottom: 4, margin: '0 0 4px' },
  overviewText: { color: '#cbd5e1', fontSize: 12, lineHeight: '18px', padding: '6px 8px 0', margin: 0 },

  footer: { display: 'flex', flexDirection: 'column', alignItems: 'center', margin: '12px 0', gap: 10, padding: '0 12px' },
  emptyState: { padding: '40px 24px', display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12 },
  emptyStateTitle: { color: '#e5e7eb', fontSize: 16, fontWeight: 700, textAlign: 'center', margin: 0 },
  emptyStateText: { color: '#94a3b8', fontSize: 13, lineHeight: '19px', textAlign: 'center', margin: 0 },
  emptyStateButton: { flex: 'none', minWidth: 150, padding: '10px 18px' },

  menuBackdrop: { position: 'fixed', inset: 0, backgroundColor: 'rgba(2,6,23,0.35)', display: 'flex', alignItems: 'flex-start', justifyContent: 'flex-end', paddingTop: 56, paddingRight: 16, zIndex: 1000 },
  menuPanel: { width: 170, border: '1px solid #1f2937', borderRadius: 10, overflow: 'hidden', backgroundColor: '#111827' },
  menuItem: { padding: '12px 14px', borderBottom: '1px solid #1f2937', cursor: 'pointer', backgroundColor: 'transparent', width: '100%', textAlign: 'left', border: 'none', borderBottom: '1px solid #1f2937', display: 'block' },
  menuItemText: { color: '#e5e7eb', fontWeight: 600, margin: 0 },

  toWatchList: { padding: 12, display: 'flex', flexDirection: 'column', gap: 10 },
  toWatchCard: { border: '1px solid #1f2937', borderRadius: 12, backgroundColor: '#111827', display: 'flex', flexDirection: 'row', overflow: 'hidden' },
  toWatchPoster: { width: 96, height: 144, backgroundColor: '#0f172a', objectFit: 'cover', flexShrink: 0, display: 'block' },
  toWatchMeta: { flex: 1, padding: 10, display: 'flex', flexDirection: 'column' },
  toWatchActions: { display: 'flex', flexDirection: 'row', marginTop: 8, justifyContent: 'space-between' },
  removeButton: { border: '1px solid #334155', backgroundColor: '#0f172a' },
  emptyText: { color: '#94a3b8', textAlign: 'center', marginTop: 30 },

  modalBackdrop: { position: 'fixed', inset: 0, backgroundColor: 'rgba(2,6,23,0.8)', display: 'flex', flexDirection: 'column', justifyContent: 'flex-end', zIndex: 1000 },
  modalPanel: { backgroundColor: '#111827', borderTopLeftRadius: 16, borderTopRightRadius: 16, padding: 14, maxHeight: '72%', display: 'flex', flexDirection: 'column' },
  modalTitle: { color: '#e5e7eb', fontWeight: 700, fontSize: 18, margin: '0 0 8px' },
  genreList: { marginBottom: 12, overflowY: 'auto', flex: 1 },
  genreItem: { display: 'flex', flexDirection: 'row', justifyContent: 'space-between', borderBottom: '1px solid #1f2937', padding: '10px 0', cursor: 'pointer', backgroundColor: 'transparent', width: '100%', border: 'none', borderBottom: '1px solid #1f2937' },
  genreItemText: { color: '#e5e7eb', margin: 0 },
  genreCheckOn: { color: '#22d3ee', fontWeight: 700, margin: 0 },
  genreCheckOff: { color: '#64748b', margin: 0 },
};
